#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {[0] = LAYOUT_split_3x6_5(LT(4, KC_ESC), KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_MINS, KC_EQL, MO(3), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_LSFT, KC_MPLY, KC_MNXT, KC_DEL, KC_N, KC_M, KC_P, KC_LBRC, KC_RBRC, KC_NUHS, KC_LSFT, KC_LGUI, MO(2), KC_LCTL, KC_ENT, KC_BSPC, KC_SPC, MO(1), KC_RSFT, KC_LALT),
                                                              [1] = LAYOUT_split_3x6_5(KC_GRV, KC_NO, KC_NO, KC_UP, KC_TAB, KC_NO, KC_F6, KC_NO, KC_NO, KC_PSCR, KC_NO, KC_F12, KC_TRNS, KC_ESC, KC_LEFT, KC_DOWN, KC_RGHT, KC_NO, KC_NO, KC_HOME, KC_END, KC_PGUP, KC_PGDN, KC_NO, KC_TRNS, KC_NO, KC_APP, KC_NO, KC_CAPS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TAB, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
                                                              [2] = LAYOUT_split_3x6_5(KC_TRNS, RALT(KC_2), LSFT(KC_5), KC_MINS, LSFT(KC_0), LSFT(KC_DOT), RALT(KC_7), RALT(KC_0), RALT(KC_8), RALT(KC_9), LSFT(KC_NUHS), KC_EQL, KC_TRNS, LSFT(KC_8), LSFT(KC_1), LSFT(KC_MINS), LSFT(KC_2), LSFT(KC_SLSH), KC_NUHS, KC_COMM, KC_DOT, KC_SLSH, LSFT(KC_9), LSFT(KC_RBRC), KC_TRNS, RALT(KC_4), LSFT(KC_3), RALT(KC_RBRC), LSFT(KC_7), LSFT(KC_COMM), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NUBS, LSFT(KC_NUBS), LSFT(KC_6), KC_GRV, LSFT(KC_EQL), RALT(KC_EQL), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
                                                              [3] = LAYOUT_split_3x6_5(KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_PSLS, KC_7, KC_8, KC_9, KC_PMNS, KC_NO, KC_TRNS, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_PAST, KC_4, KC_5, KC_6, KC_PPLS, KC_NO, KC_TRNS, KC_F11, KC_F12, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_ENT, KC_1, KC_2, KC_3, KC_PEQL, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_0, KC_COMM, KC_DOT),
                                                              [4] = LAYOUT_split_3x6_5(KC_NO, RGB_MOD, RGB_HUI, RGB_SAI, RGB_VAI, RGB_SPI, BL_TOGG, BL_STEP, BL_BRTG, BL_ON, BL_UP, KC_NO, RGB_M_B, RGB_RMOD, RGB_HUD, RGB_SAD, RGB_VAD, RGB_SPD, KC_NO, KC_NO, KC_NO, BL_OFF, BL_DOWN, KC_NO, RGB_M_R, RGB_M_SW, RGB_M_SN, RGB_M_K, RGB_M_X, RGB_M_G, RGB_M_T, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_TOG, RGB_M_P, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)

bool rgb_matrix_indicators_advanced_user(uint8_t led_min, uint8_t led_max) {
    switch (get_highest_layer(layer_state | default_layer_state)) {
        case 3:

            // red
            // rgb_matrix_set_color(0, 255, 0, 0); // ug1
            // rgb_matrix_set_color(1, 255, 0, 0); // ug2
            // rgb_matrix_set_color(2, 255, 0, 0); // ug3
            // rgb_matrix_set_color(3, 255, 0, 0); // ug4
            // rgb_matrix_set_color(4, 255, 0, 0); // ug5
            // rgb_matrix_set_color(5, 255, 0, 0); // ug6
            // fire nederste til høyre
            // rgb_matrix_set_color(6, 255, 0, 0);
            // rgb_matrix_set_color(7, 255, 0, 0);
            // rgb_matrix_set_color(8, 255, 0, 0);
            // rgb_matrix_set_color(9, 255, 0, 0);

            // // green
            // rgb_matrix_set_color(10, 0, 255, 0);
            // rgb_matrix_set_color(11, 0, 255, 0);
            // rgb_matrix_set_color(12, 0, 255, 0);
            // rgb_matrix_set_color(13, 0, 255, 0);
            // rgb_matrix_set_color(14, 0, 255, 0);
            // rgb_matrix_set_color(15, 0, 255, 0);
            // rgb_matrix_set_color(16, 0, 255, 0);
            // rgb_matrix_set_color(17, 0, 255, 0);
            // rgb_matrix_set_color(18, 0, 255, 0);
            // rgb_matrix_set_color(19, 0, 255, 0);

            // // blue
            // rgb_matrix_set_color(20, 0, 0, 255);
            // rgb_matrix_set_color(21, 0, 0, 255);
            // rgb_matrix_set_color(22, 0, 0, 255);
            // rgb_matrix_set_color(23, 0, 0, 255);
            // rgb_matrix_set_color(24, 0, 0, 255);
            // rgb_matrix_set_color(25, 0, 0, 255);
            // rgb_matrix_set_color(26, 0, 0, 255);
            // rgb_matrix_set_color(27, 0, 0, 255);
            // rgb_matrix_set_color(28, 0, 0, 255);
            // rgb_matrix_set_color(29, 0, 0, 255);

            // // esc, right underglow, 3 nederste til venstre
            // // yellow
            // rgb_matrix_set_color(30, 255, 255, 0); // esc
            // rgb_matrix_set_color(31, 255, 255, 0); // ug1
            // rgb_matrix_set_color(32, 255, 255, 0); // ug2
            // rgb_matrix_set_color(33, 255, 255, 0); // ug3
            // rgb_matrix_set_color(34, 255, 255, 0); // ug4
            // rgb_matrix_set_color(35, 255, 255, 0); // ug5
            // rgb_matrix_set_color(36, 255, 255, 0); // ug6
            // rgb_matrix_set_color(37, 255, 255, 0);
            // rgb_matrix_set_color(38, 255, 255, 0);
            // rgb_matrix_set_color(39, 255, 255, 0); // 0

            // // cyan
            // rgb_matrix_set_color(40, 0, 255, 255); // ,
            // rgb_matrix_set_color(41, 0, 255, 255); // .
            // rgb_matrix_set_color(42, 0, 255, 255);
            // rgb_matrix_set_color(43, 0, 255, 255);
            // rgb_matrix_set_color(44, 0, 255, 255); // enter
            // rgb_matrix_set_color(45, 0, 255, 255); // 1
            // rgb_matrix_set_color(46, 0, 255, 255); // 2
            // rgb_matrix_set_color(47, 0, 255, 255); // 3
            // rgb_matrix_set_color(48, 0, 255, 255);
            // rgb_matrix_set_color(49, 0, 255, 255);

            // // magenta
            // rgb_matrix_set_color(50, 255, 0, 255); // *
            // rgb_matrix_set_color(51, 255, 0, 255); // 4
            // rgb_matrix_set_color(52, 255, 0, 255); // 5
            // rgb_matrix_set_color(53, 255, 0, 255); // 6
            // rgb_matrix_set_color(54, 255, 0, 255); // +
            // rgb_matrix_set_color(55, 255, 0, 255);
            // rgb_matrix_set_color(56, 255, 0, 255); // /
            // rgb_matrix_set_color(57, 255, 0, 255); // 7
            // rgb_matrix_set_color(58, 255, 0, 255); // 8
            // rgb_matrix_set_color(59, 255, 0, 255); // 9

            // // white
            // rgb_matrix_set_color(60, 255, 255, 255); // -
            // rgb_matrix_set_color(61, 255, 255, 255);

            // turn off 6 - 61, exclude 31 - 36
            for (uint8_t i = 6; i <= 61; i++) {
                if (i < 31 || i > 36) {
                    rgb_matrix_set_color(i, 0, 0, 0);
                }
            }

            // purple
            rgb_matrix_set_color(40, 0, 128, 255); // ,

            // pink
            rgb_matrix_set_color(41, 255, 0, 255); // .

            // yellow
            rgb_matrix_set_color(44, 255, 255, 0); // enter

            // blue
            rgb_matrix_set_color(50, 0, 0, 255); // *

            // green
            rgb_matrix_set_color(54, 0, 255, 0); // +

            // red
            rgb_matrix_set_color(60, 255, 0, 0); // -

            // orange
            rgb_matrix_set_color(56, 255, 69, 0); // /

            // white
            rgb_matrix_set_color(39, 255, 255, 255); // 0
            rgb_matrix_set_color(45, 255, 255, 255); // 1
            rgb_matrix_set_color(46, 255, 255, 255); // 2
            rgb_matrix_set_color(47, 255, 255, 255); // 3
            rgb_matrix_set_color(51, 255, 255, 255); // 4
            rgb_matrix_set_color(52, 255, 255, 255); // 5
            rgb_matrix_set_color(53, 255, 255, 255); // 6
            rgb_matrix_set_color(57, 255, 255, 255); // 7
            rgb_matrix_set_color(58, 255, 255, 255); // 8
            rgb_matrix_set_color(59, 255, 255, 255); // 9

            break;
        default:
            break;
    }
    return false;
}
